// SRS (Super Rotation System) piece definitions.
// Coordinates are (x, y) with x = column (right) and y = row (down).
// Each piece lives in a bounding box (3x3 for J/L/S/T/Z, 4x4 for I/O);
// rotation states are generated by rotating the spawn state 90° CW in the box.

export type Tetromino = "I" | "O" | "T" | "S" | "Z" | "J" | "L";

export const TETROMINOES: Tetromino[] = ["I", "O", "T", "S", "Z", "J", "L"];

export const COLORS: Record<Tetromino, string> = {
  I: "#31c7ef", // cyan
  O: "#f5d33f", // yellow
  T: "#a45ce6", // purple
  S: "#43d96b", // green
  Z: "#ef5561", // red
  J: "#4a6cf5", // blue
  L: "#f58b31", // orange
};

type Cell = [number, number];

// Spawn (state 0) cell positions in the bounding box.
const SPAWN: Record<Tetromino, Cell[]> = {
  I: [
    [0, 1],
    [1, 1],
    [2, 1],
    [3, 1],
  ],
  O: [
    [1, 0],
    [2, 0],
    [1, 1],
    [2, 1],
  ],
  T: [
    [1, 0],
    [0, 1],
    [1, 1],
    [2, 1],
  ],
  S: [
    [1, 0],
    [2, 0],
    [0, 1],
    [1, 1],
  ],
  Z: [
    [0, 0],
    [1, 0],
    [1, 1],
    [2, 1],
  ],
  J: [
    [0, 0],
    [0, 1],
    [1, 1],
    [2, 1],
  ],
  L: [
    [2, 0],
    [0, 1],
    [1, 1],
    [2, 1],
  ],
};

export const BOX: Record<Tetromino, number> = {
  I: 4,
  O: 4,
  T: 3,
  S: 3,
  Z: 3,
  J: 3,
  L: 3,
};

/** Rotate a cell 90° CW within an n×n box: (x, y) -> (n-1-y, x). */
function rotateCW(cells: Cell[], n: number): Cell[] {
  return cells.map(([x, y]) => [n - 1 - y, x]);
}

/**
 * ROTATION[type][rot] = the 4 cells of `type` in rotation state `rot`
 * (0 = spawn, 1 = R, 2 = 2, 3 = L).
 */
export const ROTATION: Record<Tetromino, Cell[][]> = (() => {
  const out = {} as Record<Tetromino, Cell[][]>;
  for (const t of TETROMINOES) {
    const n = BOX[t];
    // The O piece is symmetric — all four states are identical.
    const states: Cell[][] = [SPAWN[t].map(([x, y]) => [x, y])];
    for (let i = 1; i < 4; i++) {
      states.push(
        t === "O"
          ? states[0].map(([x, y]) => [x, y])
          : rotateCW(states[i - 1], n)
      );
    }
    out[t] = states;
  }
  return out;
})();

/**
 * SRS wall-kick offsets, expressed in y-DOWN coordinates (board space).
 * KICKS[table][fromRot][toRot] = candidate (dx, dy) offsets, tried in order
 * (the first non-colliding offset wins; (0,0) is always first).
 */
type Kick = [number, number];
export const KICKS: {
  normal: Record<number, Record<number, Kick[]>>;
  i: Record<number, Record<number, Kick[]>>;
} = {
  // J, L, S, T, Z — standard SRS kick data (y values negated from the
  // wiki's y-up convention to match our y-down board).
  normal: {
    0: {
      1: [
        [0, 0],
        [-1, 0],
        [-1, -1],
        [0, 2],
        [-1, 2],
      ],
      3: [
        [0, 0],
        [1, 0],
        [1, -1],
        [0, 2],
        [1, 2],
      ],
    },
    1: {
      0: [
        [0, 0],
        [1, 0],
        [1, 1],
        [0, -2],
        [1, -2],
      ],
      2: [
        [0, 0],
        [-1, 0],
        [-1, 1],
        [0, -2],
        [-1, -2],
      ],
    },
    2: {
      1: [
        [0, 0],
        [1, 0],
        [1, -1],
        [0, 2],
        [1, 2],
      ],
      3: [
        [0, 0],
        [-1, 0],
        [-1, 1],
        [0, 2],
        [-1, 2],
      ],
    },
    3: {
      0: [
        [0, 0],
        [-1, 0],
        [-1, 1],
        [0, 2],
        [-1, 2],
      ],
      2: [
        [0, 0],
        [1, 0],
        [1, 1],
        [0, -2],
        [1, -2],
      ],
    },
  },
  // I piece — SRS I-kick data (y-down).
  i: {
    0: {
      1: [
        [0, 0],
        [-2, 0],
        [1, 0],
        [-2, 1],
        [1, -2],
      ],
      3: [
        [0, 0],
        [-1, 0],
        [2, 0],
        [-1, 2],
        [2, -1],
      ],
    },
    1: {
      0: [
        [0, 0],
        [2, 0],
        [-1, 0],
        [2, -1],
        [-1, 2],
      ],
      2: [
        [0, 0],
        [-1, 0],
        [2, 0],
        [-1, -2],
        [2, 1],
      ],
    },
    2: {
      1: [
        [0, 0],
        [1, 0],
        [-2, 0],
        [1, -2],
        [-2, 1],
      ],
      3: [
        [0, 0],
        [2, 0],
        [-1, 0],
        [2, -1],
        [-1, 2],
      ],
    },
    3: {
      0: [
        [0, 0],
        [1, 0],
        [-2, 0],
        [1, 2],
        [-2, -1],
      ],
      2: [
        [0, 0],
        [-2, 0],
        [1, 0],
        [-2, 1],
        [1, -2],
      ],
    },
  },
};
